version: '3'

tasks:

  default:
    deps: [main]

  main:
    aliases: ["m"]
    cmds:
     - cd cpp && task
     - cd python_test && task

  clean:
    aliases: ["c"]
    cmds:
     - cd cpp && task clean
     - cd python_test && task clean