version: '3'

tasks:

  init:
    cmds:
      - uv sync

  fmu:
    cmds:
      - uv run z_create_fmu.py

  build:
    aliases: ["b"]
    cmds:
      - cd cpp && task build
      - uv run z_create_fmu.py
      
  all:
    aliases: ["a"]
    deps: ["build"]
    cmds:
     - cd python_test && task

  test:
    aliases: ["t"]
    cmds:
     - cd python_test && task
     
  docker:
    aliases: ["d"]
    cmds:
      - docker build -t python_fmu_test .
      - docker run -v .\\z_fmu_out:/app/z_fmu_out python_fmu_test

  clean:
    aliases: ["c"]
    cmds:
     - cd cpp && task clean
     - cd python_test && task clean
     - python z_clean.py z_fmu_out/
  
  clean_all:
    aliases: ["ca"]
    deps: ["clean"]
    cmds:
     - python z_clean.py .venv/
