version: '3'

tasks:

  default:
    deps: [main]

  main:
    aliases: ["m"]
    cmds:
     - cd cpp && task
     - cd python_test && task

     
  build:
    aliases: ["b"]
    cmds:
      - cd cpp && task build
     
  docker:
    aliases: ["d"]
    cmds:
      - docker build -t python_fmu_test .
      - docker run -v .\\cpp_fmu_out:/app/cpp_fmu_out python_fmu_test

  clean:
    aliases: ["c"]
    cmds:
     - cd cpp && task clean
     - cd python_test && task clean
     - rm -rf cpp_fmu_out/
    ignore_error: true