[project]
name = "cpp-fmu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fmpy>=0.3.22",
    "matplotlib>=3.10.1",
]
