version: '3'

tasks:

  default:
    deps: [main]

  main:
    aliases: ["m"]
    cmds:
     - uv run main.py

  testpy:
    cmds:
     - python main.py

  clean:
    aliases: ["c"]
    cmds:
     - 

    ignore_error: true