version: '3'

tasks:
  default:
    deps: ["b"]

  build:
    aliases: ["b"]
    cmds:
      # building libraries
      - uv run -m ziglang build

  clean:
    aliases: ["c"]
    cmds:
      - python ../z_clean.py .zig-cache
      - python ../z_clean.py zig-out
