version: '3'

tasks:
  default:
    deps: ["b"]

  build:
    aliases: ["b"]
    cmds:
      # building libraries
      - uv run -m ziglang build

  clean:
    aliases: ["c"]
    cmds:
      - rm -rf .zig-cache
      - rm -rf zig-out
      - rm -rf z_fmu_out
    ignore_error: true
