version: '3'

tasks:
  default:
    deps: ["b"]

  build:
    aliases: ["b"]
    cmds:
      # building libraries
      - zig build
      # creating fmu
      - mkdir -p z_fmu_out/binaries/win32
      - mkdir -p z_fmu_out/binaries/win64
      - mkdir -p z_fmu_out/binaries/linux64
      - cp zig-out/x86-windows/BouncingBall.dll z_fmu_out/binaries/win32
      - cp zig-out/x86_64-windows/BouncingBall.dll z_fmu_out/binaries/win64
      - cp zig-out/x86_64-linux-gnu/libBouncingBall.so z_fmu_out/binaries/linux64/BouncingBall.so
      - cp -r src/*.cpp z_fmu_out/
      - cp -r src/modelDescription.xml z_fmu_out/
      - 7z a -tzip BouncingBall.fmu ./z_fmu_out/*
      # copying result to `fmu_out`
      - mkdir -p ../cpp_fmu_out
      - cp BouncingBall.fmu ../cpp_fmu_out/

  clean:
    aliases: ["c"]
    cmds:
      - rm -rf .zig-cache
      - rm -rf zig-out
      - rm -rf z_fmu_out
      - rm -rf *.fmu
    ignore_error: true
